title: The role of cloud computing in data engineering
author: Subhopriyo Das
email: Subhopriyo.Das@mastechinfotrellis.com
description: > # this means to ignore newlines until "baseurl:"
  [My content goes here]
theme: jekyll-theme-minimal
# social links
twitter_username: subhopriyo # DO NOT include the @ character, or else the build will fail!
github_username:  subhopriyo-das # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
